//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelOfString", Namespace="http://tempuri.org/")]
    public partial class ResponseModelOfString : object
    {
        
        private string DataField;
        
        private int resultCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestWs.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/create_new_user", ReplyAction="*")]
        TestWs.create_new_userResponse create_new_user(TestWs.create_new_userRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/create_new_user", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWs.create_new_userResponse> create_new_userAsync(TestWs.create_new_userRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        TestWs.LoginResponse Login(TestWs.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWs.LoginResponse> LoginAsync(TestWs.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name paymentMethod from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Allorders", ReplyAction="*")]
        TestWs.AllordersResponse Allorders(TestWs.AllordersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Allorders", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWs.AllordersResponse> AllordersAsync(TestWs.AllordersRequest request);
        
        // CODEGEN: Generating message contract since element name Create_New_OrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_New_Order", ReplyAction="*")]
        TestWs.Create_New_OrderResponse Create_New_Order(TestWs.Create_New_OrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_New_Order", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWs.Create_New_OrderResponse> Create_New_OrderAsync(TestWs.Create_New_OrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class create_new_userRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create_new_user", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.create_new_userRequestBody Body;
        
        public create_new_userRequest()
        {
        }
        
        public create_new_userRequest(TestWs.create_new_userRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class create_new_userRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime createdDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userEmail;
        
        public create_new_userRequestBody()
        {
        }
        
        public create_new_userRequestBody(string username, string password, System.DateTime createdDate, string userEmail)
        {
            this.username = username;
            this.password = password;
            this.createdDate = createdDate;
            this.userEmail = userEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class create_new_userResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create_new_userResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.create_new_userResponseBody Body;
        
        public create_new_userResponse()
        {
        }
        
        public create_new_userResponse(TestWs.create_new_userResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class create_new_userResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestWs.ResponseModelOfString create_new_userResult;
        
        public create_new_userResponseBody()
        {
        }
        
        public create_new_userResponseBody(TestWs.ResponseModelOfString create_new_userResult)
        {
            this.create_new_userResult = create_new_userResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.LoginRequestBody Body;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(TestWs.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody()
        {
        }
        
        public LoginRequestBody(string email, string password)
        {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.LoginResponseBody Body;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(TestWs.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestWs.ResponseModelOfString LoginResult;
        
        public LoginResponseBody()
        {
        }
        
        public LoginResponseBody(TestWs.ResponseModelOfString LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllordersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Allorders", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.AllordersRequestBody Body;
        
        public AllordersRequest()
        {
        }
        
        public AllordersRequest(TestWs.AllordersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllordersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string paymentMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> scheduleID;
        
        public AllordersRequestBody()
        {
        }
        
        public AllordersRequestBody(System.Nullable<int> OrderID, string paymentMethod, System.Nullable<int> scheduleID)
        {
            this.OrderID = OrderID;
            this.paymentMethod = paymentMethod;
            this.scheduleID = scheduleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllordersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllordersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.AllordersResponseBody Body;
        
        public AllordersResponse()
        {
        }
        
        public AllordersResponse(TestWs.AllordersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllordersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestWs.ResponseModelOfString AllordersResult;
        
        public AllordersResponseBody()
        {
        }
        
        public AllordersResponseBody(TestWs.ResponseModelOfString AllordersResult)
        {
            this.AllordersResult = AllordersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_New_OrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_New_Order", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.Create_New_OrderRequestBody Body;
        
        public Create_New_OrderRequest()
        {
        }
        
        public Create_New_OrderRequest(TestWs.Create_New_OrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_New_OrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int orderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime orderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int type;
        
        public Create_New_OrderRequestBody()
        {
        }
        
        public Create_New_OrderRequestBody(int userID, int orderNumber, System.DateTime orderDate, decimal price, int type)
        {
            this.userID = userID;
            this.orderNumber = orderNumber;
            this.orderDate = orderDate;
            this.price = price;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_New_OrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_New_OrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestWs.Create_New_OrderResponseBody Body;
        
        public Create_New_OrderResponse()
        {
        }
        
        public Create_New_OrderResponse(TestWs.Create_New_OrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_New_OrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestWs.ResponseModelOfString Create_New_OrderResult;
        
        public Create_New_OrderResponseBody()
        {
        }
        
        public Create_New_OrderResponseBody(TestWs.ResponseModelOfString Create_New_OrderResult)
        {
            this.Create_New_OrderResult = Create_New_OrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface WebService1SoapChannel : TestWs.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TestWs.WebService1Soap>, TestWs.WebService1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWs.create_new_userResponse TestWs.WebService1Soap.create_new_user(TestWs.create_new_userRequest request)
        {
            return base.Channel.create_new_user(request);
        }
        
        public TestWs.ResponseModelOfString create_new_user(string username, string password, System.DateTime createdDate, string userEmail)
        {
            TestWs.create_new_userRequest inValue = new TestWs.create_new_userRequest();
            inValue.Body = new TestWs.create_new_userRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.createdDate = createdDate;
            inValue.Body.userEmail = userEmail;
            TestWs.create_new_userResponse retVal = ((TestWs.WebService1Soap)(this)).create_new_user(inValue);
            return retVal.Body.create_new_userResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWs.create_new_userResponse> TestWs.WebService1Soap.create_new_userAsync(TestWs.create_new_userRequest request)
        {
            return base.Channel.create_new_userAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWs.create_new_userResponse> create_new_userAsync(string username, string password, System.DateTime createdDate, string userEmail)
        {
            TestWs.create_new_userRequest inValue = new TestWs.create_new_userRequest();
            inValue.Body = new TestWs.create_new_userRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.createdDate = createdDate;
            inValue.Body.userEmail = userEmail;
            return ((TestWs.WebService1Soap)(this)).create_new_userAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWs.LoginResponse TestWs.WebService1Soap.Login(TestWs.LoginRequest request)
        {
            return base.Channel.Login(request);
        }
        
        public TestWs.ResponseModelOfString Login(string email, string password)
        {
            TestWs.LoginRequest inValue = new TestWs.LoginRequest();
            inValue.Body = new TestWs.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            TestWs.LoginResponse retVal = ((TestWs.WebService1Soap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWs.LoginResponse> TestWs.WebService1Soap.LoginAsync(TestWs.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWs.LoginResponse> LoginAsync(string email, string password)
        {
            TestWs.LoginRequest inValue = new TestWs.LoginRequest();
            inValue.Body = new TestWs.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((TestWs.WebService1Soap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWs.AllordersResponse TestWs.WebService1Soap.Allorders(TestWs.AllordersRequest request)
        {
            return base.Channel.Allorders(request);
        }
        
        public TestWs.ResponseModelOfString Allorders(System.Nullable<int> OrderID, string paymentMethod, System.Nullable<int> scheduleID)
        {
            TestWs.AllordersRequest inValue = new TestWs.AllordersRequest();
            inValue.Body = new TestWs.AllordersRequestBody();
            inValue.Body.OrderID = OrderID;
            inValue.Body.paymentMethod = paymentMethod;
            inValue.Body.scheduleID = scheduleID;
            TestWs.AllordersResponse retVal = ((TestWs.WebService1Soap)(this)).Allorders(inValue);
            return retVal.Body.AllordersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWs.AllordersResponse> TestWs.WebService1Soap.AllordersAsync(TestWs.AllordersRequest request)
        {
            return base.Channel.AllordersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWs.AllordersResponse> AllordersAsync(System.Nullable<int> OrderID, string paymentMethod, System.Nullable<int> scheduleID)
        {
            TestWs.AllordersRequest inValue = new TestWs.AllordersRequest();
            inValue.Body = new TestWs.AllordersRequestBody();
            inValue.Body.OrderID = OrderID;
            inValue.Body.paymentMethod = paymentMethod;
            inValue.Body.scheduleID = scheduleID;
            return ((TestWs.WebService1Soap)(this)).AllordersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWs.Create_New_OrderResponse TestWs.WebService1Soap.Create_New_Order(TestWs.Create_New_OrderRequest request)
        {
            return base.Channel.Create_New_Order(request);
        }
        
        public TestWs.ResponseModelOfString Create_New_Order(int userID, int orderNumber, System.DateTime orderDate, decimal price, int type)
        {
            TestWs.Create_New_OrderRequest inValue = new TestWs.Create_New_OrderRequest();
            inValue.Body = new TestWs.Create_New_OrderRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.orderNumber = orderNumber;
            inValue.Body.orderDate = orderDate;
            inValue.Body.price = price;
            inValue.Body.type = type;
            TestWs.Create_New_OrderResponse retVal = ((TestWs.WebService1Soap)(this)).Create_New_Order(inValue);
            return retVal.Body.Create_New_OrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWs.Create_New_OrderResponse> TestWs.WebService1Soap.Create_New_OrderAsync(TestWs.Create_New_OrderRequest request)
        {
            return base.Channel.Create_New_OrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWs.Create_New_OrderResponse> Create_New_OrderAsync(int userID, int orderNumber, System.DateTime orderDate, decimal price, int type)
        {
            TestWs.Create_New_OrderRequest inValue = new TestWs.Create_New_OrderRequest();
            inValue.Body = new TestWs.Create_New_OrderRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.orderNumber = orderNumber;
            inValue.Body.orderDate = orderDate;
            inValue.Body.price = price;
            inValue.Body.type = type;
            return ((TestWs.WebService1Soap)(this)).Create_New_OrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44307/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44307/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
